apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-zvud
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0018-tenant/tkrw-pr712-0075-0018-app/devfile-sample-zvud@sha256:9507b87cbdd28e4f89a2681fb7057091553e3df771b5c2ca37ce59bbebe1d1c5
        name: my-nodejs
        resources: {}
status: {}
